# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=5000
SAVEHIST=5000
setopt appendhistory autocd extendedglob nomatch notify
bindkey -v
# End of lines configured by zsh-newuser-install

source ~/.dotfiles/zsh/aliases
source ~/.zsh_plugins.sh

export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/dev/python
source /usr/bin/virtualenvwrapper_lazy.sh

export KEYTIMEOUT=1
export SPACESHIP_VI_MODE_INSERT='i'
export SPACESHIP_VI_MODE_NORMAL='n'

export VISUAL="vi"
export EDITOR="vi"
